-- ============================================================
-- DDL para Oracle (Execução Direta no DBeaver) - Projeto Voltz
-- Contém: DROP, CREATE e ALTER (adição de constraints PK/FK/CHECK)
-- ============================================================

DROP TABLE relatorio CASCADE CONSTRAINTS PURGE;
DROP TABLE autenticacao CASCADE CONSTRAINTS PURGE;
DROP TABLE transacao CASCADE CONSTRAINTS PURGE;
DROP TABLE carteira CASCADE CONSTRAINTS PURGE;
DROP TABLE usuario CASCADE CONSTRAINTS PURGE;
DROP TABLE cripto_ativo CASCADE CONSTRAINTS PURGE;
DROP TABLE empresa CASCADE CONSTRAINTS PURGE;
DROP TABLE pessoa CASCADE CONSTRAINTS PURGE;
DROP TABLE permissao CASCADE CONSTRAINTS PURGE;


-- ============================================================
-- 1. CREATE TABLES
-- ============================================================

CREATE TABLE permissao (
    id_permissao NUMBER,
    nome         VARCHAR2(50) NOT NULL,
    descricao    VARCHAR2(255),
    CONSTRAINT pk_permissao PRIMARY KEY (id_permissao)
);

CREATE TABLE pessoa (
    id_pessoa        NUMBER,
    nome             VARCHAR2(100) NOT NULL,
    cpf              VARCHAR2(11) UNIQUE NOT NULL,
    email            VARCHAR2(100) UNIQUE NOT NULL,
    data_nascimento  DATE,
    CONSTRAINT pk_pessoa PRIMARY KEY (id_pessoa)
);

CREATE TABLE empresa (
    id_empresa     NUMBER,
    razao_social   VARCHAR2(150) NOT NULL,
    cnpj           VARCHAR2(14) UNIQUE NOT NULL,
    email_contato  VARCHAR2(100),
    CONSTRAINT pk_empresa PRIMARY KEY (id_empresa)
);

CREATE TABLE usuario (
    id_usuario    NUMBER,
    login         VARCHAR2(50) NOT NULL UNIQUE,
    senha         VARCHAR2(255) NOT NULL,
    id_pessoa     NUMBER,
    id_empresa    NUMBER,
    id_permissao  NUMBER NOT NULL,
    status        VARCHAR2(20) DEFAULT 'ATIVO',
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);


CREATE TABLE cripto_ativo (
    id_cripto      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    nome           VARCHAR2(50) NOT NULL,
    sigla          VARCHAR2(10) UNIQUE NOT NULL,
    cotacao_atual  NUMBER(15, 2) NOT NULL,
    CONSTRAINT pk_cripto_ativo PRIMARY KEY (id_cripto)
);

CREATE TABLE carteira (
    id_carteira  NUMBER,
    id_usuario   NUMBER NOT NULL,
    saldo_reais  NUMBER(15, 2) DEFAULT 0.00,
    CONSTRAINT pk_carteira PRIMARY KEY (id_carteira)
);

CREATE TABLE transacao (
    id_transacao    NUMBER,
    id_carteira     NUMBER NOT NULL,
    id_cripto       NUMBER NOT NULL,
    tipo_operacao   VARCHAR2(20) NOT NULL,
    quantidade      NUMBER(18, 8) NOT NULL,
    valor_unidade   NUMBER(15, 2) NOT NULL,
    data_transacao  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_transacao PRIMARY KEY (id_transacao)
);

CREATE TABLE autenticacao (
    id_autenticacao  NUMBER,
    id_usuario       NUMBER NOT NULL,
    token_sessao     VARCHAR2(255) NOT NULL,
    data_login       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_origem        VARCHAR2(45),
    CONSTRAINT pk_autenticacao PRIMARY KEY (id_autenticacao)
);

CREATE TABLE relatorio (
    id_relatorio    NUMBER,
    id_usuario      NUMBER NOT NULL,
    tipo_relatorio  VARCHAR2(50) NOT NULL,
    data_geracao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_relatorio PRIMARY KEY (id_relatorio)
);


-- ============================================================
-- 2. ALTER TABLE - Chaves estrangeiras (FK)
-- ============================================================

ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa);

ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id_empresa);

ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_permissao FOREIGN KEY (id_permissao) REFERENCES permissao(id_permissao);

ALTER TABLE carteira
    ADD CONSTRAINT fk_carteira_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);

ALTER TABLE transacao
    ADD CONSTRAINT fk_transacao_carteira FOREIGN KEY (id_carteira) REFERENCES carteira(id_carteira);

ALTER TABLE transacao
    ADD CONSTRAINT fk_transacao_cripto FOREIGN KEY (id_cripto) REFERENCES cripto_ativo(id_cripto);

ALTER TABLE autenticacao
    ADD CONSTRAINT fk_autenticacao_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);

ALTER TABLE relatorio
    ADD CONSTRAINT fk_relatorio_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);


-- ============================================================
-- 3. ALTER TABLE - Regras de negócio (CHECK)
-- ============================================================

ALTER TABLE usuario
    ADD CONSTRAINT ck_usuario_status CHECK (status IN ('ATIVO', 'INATIVO'));

ALTER TABLE transacao
    ADD CONSTRAINT ck_transacao_tipo CHECK (tipo_operacao IN ('COMPRA', 'VENDA'));
